# Auto-generated with h2o

complete -c agat_sp_extract_sequences.pl -l "alternative_start_codon" -l "asc" -d "Bolean - When activated it can affect the translation of the start codon."
complete -c agat_sp_extract_sequences.pl -l "cdna" -d "Boolean - This extract the cdna sequence (i.e reverse complement of the mRNA: transcribed sequence (devoid of introns, but containing untranslated exons, then reverse complemented)."
complete -c agat_sp_extract_sequences.pl -l "clean_final_stop" -l "cfs" -d "Boolean - The Clean Final Stop option allows removing the translation of the final stop codons that is represented by the <*> character."
complete -c agat_sp_extract_sequences.pl -l "clean_internal_stop" -l "cis" -d "Boolean - The Clean Internal Stop option allows replacing the translation of the stop codons present among the sequence that is represented by the <*> character by <X>."
complete -c agat_sp_extract_sequences.pl -l "codon" -l "table" -l "ct" -d "Integer - Allow to choose the codon table for the translation."
complete -c agat_sp_extract_sequences.pl -l "do" -s "3" -l "three" -o "down" -o "downstream" -d "Integer - It will take that number of nucleotide in more at the 3' extremity."
complete -c agat_sp_extract_sequences.pl -l "eo" -d "Boolean - Called 'extremity only', this option will extract only the adjacent parts of a feature."
complete -c agat_sp_extract_sequences.pl -s "f" -l "fasta" -d "String - Input fasta file."
complete -c agat_sp_extract_sequences.pl -l "full" -d "Boolean - This option allows dealing with feature that may span over several locations like cds or exon, in order to extract the full sequence from the start extremity of the first chunck to the end extremity of the last chunk."
complete -c agat_sp_extract_sequences.pl -s "g" -l "gff" -o "ref" -d "String - Input GTF/GFF file."
complete -c agat_sp_extract_sequences.pl -s "h" -l "help" -d "Boolean - Display this helpful text."
complete -c agat_sp_extract_sequences.pl -l "keep_attributes" -d "Boolean - The value of the attribute tags will be extracted from the feature type specified by the option --type and stored in the fasta header."
complete -c agat_sp_extract_sequences.pl -l "keep_parent_attributes" -d "Boolean - The value of the attribute tags will be extracted from the feature type specified by the option --type along with those from parent features and stored in the fasta header."
complete -c agat_sp_extract_sequences.pl -l "merge" -d "Boolean - By default, only features that span several locations (e.g. cds and utr can span over several exons) are merged together."
complete -c agat_sp_extract_sequences.pl -l "mrna" -d "Boolean - This extract the mrna sequence (i.e transcribed sequence (devoid of introns, but containing untranslated exons))."
complete -c agat_sp_extract_sequences.pl -l "ofs" -d "String - Output Fields Separator for the description field of the header of the created fasta sequences."
complete -c agat_sp_extract_sequences.pl -s "o" -l "output" -d "String - Output fasta file."
complete -c agat_sp_extract_sequences.pl -l "plus_strand_only" -d "Boolean - By default the extrated feature sequences from a minus strand is reverse complemented."
complete -c agat_sp_extract_sequences.pl -s "p" -l "protein" -l "aa" -d "Boolean - Will translate the extracted sequence in Amino acid."
complete -c agat_sp_extract_sequences.pl -l "remove_orf_offset" -l "roo" -d "Boolean - CDS can start with a phase different from 0 when a gene model is fragmented."
complete -c agat_sp_extract_sequences.pl -l "revcomp" -d "Boolean - To reverse complement the extracted sequence [default - False]."
complete -c agat_sp_extract_sequences.pl -l "split" -d "Boolean - By default, all features that span several locations (e.g. cds and utr can span over several exons) are merge together to shape the biological feature (e.g. several cds chuncks are merged to create the CDS in its whole)."
complete -c agat_sp_extract_sequences.pl -s "t" -l "type" -d "String - Define the feature you want to extract the sequence from."
complete -c agat_sp_extract_sequences.pl -l "up" -s "5" -l "five" -o "upstream" -d "Integer - It will take that number of nucleotide in more at the 5' extremity."
