# Auto-generated with h2o

complete -c plotPCA -s "h" -l "help" -d "show this help message and exit"
complete -c plotPCA -l "transpose" -d "Perform the PCA on the transposed matrix, (i.e., on the matrix where rows are samples and columns are bins/features."
complete -c plotPCA -l "rowCenter" -d "When specified, each row (bin, gene, etc.) in the matrix is centered at 0 before the PCA is computed."
complete -c plotPCA -l "corData" -o "in" -d "Coverage file (generated by multiBamSummary or multiBigwigSummary)" -r
complete -c plotPCA -l "plotFile" -s "o" -d "File name to save the plot to." -r
complete -c plotPCA -l "labels" -s "l" -d "User defined labels instead of default labels from file names." -r
complete -c plotPCA -l "plotTitle" -s "T" -d "Title of the plot, to be printed on top of the generated image." -x
complete -c plotPCA -l "plotFileFormat" -d "Image format type." -r
complete -c plotPCA -l "plotHeight" -d "Plot height in cm." -x
complete -c plotPCA -l "plotWidth" -d "Plot width in cm." -x
complete -c plotPCA -l "outFileNameData" -d "File name to which the data underlying the plot should be saved, such as myPCA.tab." -r
complete -c plotPCA -l "ntop" -d "Use only the top N most variable rows in the original matrix." -x
complete -c plotPCA -l "PCs" -d "The principal components to plot." -x
complete -c plotPCA -l "log2" -d "log2 transform the datapoints prior to computing the PCA."
complete -c plotPCA -l "colors" -d "A list of colors for the symbols." -x
complete -c plotPCA -l "markers" -d "A list of markers for the symbols." -x
complete -c plotPCA -l "version" -d "show program's version number and exit"
