# Auto-generated with h2o

complete -c psmc -s "t" -d "maximum 2N0 coalescent time [15]" -x
complete -c psmc -s "N" -d "maximum number of iterations [30]" -x
complete -c psmc -s "r" -d "initial theta/rho ratio [4]" -x
complete -c psmc -s "c" -d "CpG counts generated by cntcpg [null]" -r
complete -c psmc -s "o" -d "output file [stdout]" -r
complete -c psmc -s "i" -d "input parameter file [null]" -r
complete -c psmc -s "T" -d "initial divergence time; -1 to disable [-1]" -x
complete -c psmc -s "b" -d "bootstrap (input be preprocessed with split_psmcfa)"
complete -c psmc -s "S" -d "simulate sequence"
complete -c psmc -s "d" -d "perform decoding"
complete -c psmc -s "D" -d "print full posterior probabilities"
