complete -c show-snps -s C -d 'Do not report SNPs from alignments with an ambiguous mapping, i.e. only report SNPs where the [R] and [Q] columns equal 0 and do not output these columns'
complete -c show-snps -s h -d 'Display help information'
complete -c show-snps -s H -d 'Do not print the output header'
complete -c show-snps -s I -d 'Do not report indels'
complete -c show-snps -s l -d 'Include sequence length information in the output'
complete -c show-snps -s q -d 'Sort output lines by query IDs and SNP positions'
complete -c show-snps -s r -d 'Sort output lines by reference IDs and SNP positions'
complete -c show-snps -s S -d 'Specify which alignments to report by passing \'show-coords\' lines to stdin'
complete -c show-snps -s T -d 'Switch to tab-delimited format'
complete -c show-snps -s x -d 'Include x characters of surrounding SNP context in the output, default 0' -x
