complete -c show-diff -s f -d 'Output diff information as AMOS features'
complete -c show-diff -s h -d 'Display help information'
complete -c show-diff -s H -d 'Do not show header'
complete -c show-diff -s q -d 'Show diff information for queries'
complete -c show-diff -s r -d 'Show diff information for references (default)'
