complete -c vcfcheck -s f -l fasta-reference -d 'FASTA reference file to use to obtain primer sequences'
complete -c vcfcheck -s x -l exclude-failures -d 'If a record fails, don\'t print it.'
complete -c vcfcheck -s k -l keep-failures -d 'Print if the record fails, otherwise not.'
complete -c vcfcheck -s h -l help -d 'Print this message.'
complete -c vcfcheck -s v -l version -d 'Print version.'
