complete -c vcfinfosummarize -s f -l field -d 'Summarize this field in the INFO column'
complete -c vcfinfosummarize -s i -l info -d 'Store the computed statistic in this info field'
complete -c vcfinfosummarize -s a -l average -d 'Take the mean for field (default)'
complete -c vcfinfosummarize -s m -l median -d 'Use the median'
complete -c vcfinfosummarize -s n -l min -d 'Use the min'
complete -c vcfinfosummarize -s x -l max -d 'Use the max'
complete -c vcfinfosummarize -s h -l help -d 'Print this message'
complete -c vcfinfosummarize -s v -l version -d 'Print version'
