complete -c vcfsample2info -s f -l field -d 'Add information about this field in samples to INFO column'
complete -c vcfsample2info -s i -l info -d 'Store the computed statistic in this info field'
complete -c vcfsample2info -s a -l average -d 'Take the mean of samples for field (default)'
complete -c vcfsample2info -s m -l median -d 'Use the median'
complete -c vcfsample2info -s n -l min -d 'Use the min'
complete -c vcfsample2info -s x -l max -d 'Use the max'
